version: '3.7'

services:
  order-vegitable: 
    image: docker.io/akshaydatir/mmv-order-vegitable:0.0.1-RELEASE
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - order-network
    depends_on:
      - eureka   
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://localhost:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
         
  order-fruit: 
    image: docker.io/akshaydatir/mmv2-order-fruits:0.0.1-RELEASE
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - order-network
    depends_on:
      - eureka  
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://localhost:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      
  order: 
    image: docker.io/akshaydatir/mmv2-0rder:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8500:8500"
    networks:
      - order-network
    depends_on:
      - eureka   
      - order-fruit
      - order-vegitable
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://localhost:8761/eureka        
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      VEGITABLE_ORDER_SERVICE_HOST: http://vegitable-order
      FRUIT_ORDER_SERVICE_HOST: http://fruit-order
      
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9412:9412"
    networks:
      - order-network
          
  eureka: 
    image: docker.io/akshaydatir/mmv2-eureka:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - order-network
    
networks: 
  order-network: 
   
   
   
   
   
   